### ISSUE TITLE
[FEATURE] Update the readme accordingly

### ISSUE THREAD

**Issue by Panquesito7** [dev-protocol/docs.devprotocol.xyz#129]
**Is your feature request related to a problem? Please describe.**

We should update the readme file according to what this project is about.

**Describe the solution you'd like**

Update the readme file with proper documentation and information regarding this project.

**Describe alternatives you've considered**

None.

**Comment by vinzvinci** [comment]
Hi, thanks for raising this issue. I am cleaning the issues and PR now.

Will u be able to continue this?

**Comment by Panquesito7** [comment]
> Hi, thanks for raising this issue. I am cleaning the issues and PR now.
> 
> Will u be able to continue this?

I'm not sure if I'm gonna make it; I left this issue open for anyone to contribute. 🙂

**Comment by vinzvinci** [comment]
Okay thanks. This issue will update after migrating to 2.0 documentation theme.

**Comment by vinzvinci** [comment]
CC @osaguild, u may help with this?

**Comment by vinzvinci** [comment]
Btw, it was handled by @KukretiShubham.
