### ISSUE TITLE
[FEATURE] Setup the Gitpod ready-to-code system

### ISSUE THREAD

**Issue by Panquesito7** [dev-protocol/docs.devprotocol.xyz#130]
### Detailed description

Adding the Gitpod ready-to-code system will make the process of compiling much easier in just a single click.

### Context

This is very useful when you want Gitpod to run `npm` commands quickly for you and run the whole project quickly. It's much better than cloning the repository, reading the readme, installing the necessary tools, etc....

### Possible implementation

I already know how to set it up. It is just by creating a PR and giving [Gitpod](https://gitpod.io) access to this organization. 🙂

### Additional information

I would like to work on this. It's very easy to set it up. 😄

**Comment by vinzvinci** [comment]
Hi, will u be able to continue this?

I think it better to use yarn?

**Comment by Panquesito7** [comment]
> Hi, will u be able to continue this?
> 
> I think it better to use yarn?

Yeah, we can use Yarn if needed.

**Comment by vinzvinci** [comment]
Okay, yeah

**Comment by Panquesito7** [comment]
Should I make it or let this issue open for first-timers?

**Comment by vinzvinci** [comment]
> Should I make it or let this issue open for first-timers?

I added the `good first issue` label. If no one work on this issue for 1 week, feel free to raise PR

**Comment by Panquesito7** [comment]
No pull request. Working on it.

**Comment by Panquesito7** [comment]
Actually, it looks like there's already a `.gitpod.yml` file. Should I close this issue?

**Comment by vinzvinci** [comment]
Closing
