### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by aggre** [dev-protocol/docs.devprotocol.xyz#25]
**Is your feature request related to a problem? Please describe.**

Code snippets are monotonous and visually difficult to read.

![image](https://user-images.githubusercontent.com/1970283/121282333-45a67d80-c914-11eb-9c0b-d4292a9b16f9.png)

**Describe the solution you'd like**

Is it possible to apply syntax highlighting like INITTO?

![INITTO](https://user-images.githubusercontent.com/1970283/121282301-37f0f800-c914-11eb-91e1-0eccf87f9a0e.png)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by akashgp09** [comment]
Hi @aggre I would like to work on this :)
