### ISSUE TITLE
[OTHER] Remove docs folder

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/docs.devprotocol.xyz#282]
### What would you like to share?

Hey @aggre, would it be okay if I remove the [docs](https://github.com/dev-protocol/docs.devprotocol.xyz/tree/main/docs) directory? it confused us. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aggre** [comment]
> Hey @aggre, would it be okay if I remove the [docs](https://github.com/dev-protocol/docs.devprotocol.xyz/tree/main/docs) directory? it confused us.

Yes, of course!
