### ISSUE TITLE
bug: Error Fetching Resource (image & URL)

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/docs.devprotocol.xyz#59]
This one is on Khaos section

Found a bug:

- The image not showing
- When u click the URL, you'll get the error: Error **Fetching Resource.**

![image](https://user-images.githubusercontent.com/73097560/127099030-908474e4-465e-4150-b926-d683269d1908.png)

~~-~~

Another one 

![image](https://user-images.githubusercontent.com/73097560/127099224-dddbfd18-b297-4fcf-9f7e-f49d76075dcb.png)

**Comment by vinzvinci** [comment]
Hmm, I don't know what is the real link here, can u help @kazu80 in your free time?

**Comment by vinzvinci** [comment]
Found the bug, the image is on SVG file, that's why it's hard for the server to get the resource.

![image](https://user-images.githubusercontent.com/73097560/128300470-1af54f01-70da-4188-af86-758537bfae72.png)

**Comment by kazu80** [comment]
It was normal in my environment, so I asked Vinz to sort out the situation.
In Vinz's environment, images other than this page can be displayed

**Comment by vinzvinci** [comment]
Great! The server is fixed! Time to close the issue, I see it now ^^

**Comment by vinzvinci** [comment]
I think the server is not okay, so I think it's really better to use img not svg to that page. I'm gonna reopen this issue and fix it.

**Comment by vinzvinci** [comment]
Can u copy the image of "**How Khaos Stores Confidential**" and put it here @kazu80 


Just like this:
How Khaos Oraclizes
![image](https://user-images.githubusercontent.com/73097560/128965086-1591edc8-b404-491e-afe6-68999d62db89.png)

**Comment by kazu80** [comment]
Okay. Ill do

**Comment by kazu80** [comment]
@vinzvinci 
Please check
https://github.com/dev-protocol/docs.devprotocol.xyz/pull/71
