### ISSUE TITLE
docs: URL not found on (what is treasury)

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/docs.devprotocol.xyz#61]
Saw this on [onboard-guide](https://docs.devprotocol.xyz/stakes-social/onboard-guide/) section. English and Japan page

- The link is not working

![image](https://user-images.githubusercontent.com/73097560/127100781-52917313-d4ae-4741-a6bc-29ea2b9fe56a.png)

**Comment by kazu80** [comment]
Thanks!!
 I'll fix it

**Comment by vinzvinci** [comment]
Okeh, I'll assign this issue to you ^^

**Comment by vinzvinci** [comment]
Fixed
