### ISSUE TITLE
Feat: Documentation Website 2.0

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/docs.devprotocol.xyz#90]
I like to customize our documentation to make it clean. I'll find better templates for this.

**Comment by vinzvinci** [comment]
I think https://docusaurus.io/ is better @kazu80?

**Comment by KukretiShubham** [comment]
Hey, I would also prefer. docusaurus. Assign it to me.

**Comment by vinzvinci** [comment]
> Hey, I would also prefer. docusaurus. Assign it to me.

Goodluck and have fun with migrating xD.
